# Stage 1: Install dependencies
FROM node:14.17.3 as dependencies

WORKDIR /app

COPY package.json package-lock.json /app/

# Update npm to the latest version
RUN npm install -g npm@latest

# Specify the desired Angular version
RUN npm install @angular/cli@11.0.5 --legacy-peer-deps

RUN npm install --force

# Stage 2: Serve the application using the Angular CLI
FROM dependencies as serve

WORKDIR /app

COPY . /app

EXPOSE 4200

CMD ["npm", "start"]
