# Stage 1: Install dependencies
FROM node:14.17.3 as dependencies

WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm install

# Stage 2: Serve the application using the Angular CLI
FROM node:14.17.3 as development

WORKDIR /app

COPY . /app

EXPOSE 4200

CMD ["ng","serve"]
